### ISSUE TITLE
Update to VS 2019

### ISSUE THREAD

**Issue by dr-eck** [Skyppid/Array-Visualizer#3]
Thank you very much for updating Array Visualizer for VS 2017.  I'd really appreciate it if you would do the same for VS 2019

**Comment by Skyppid** [comment]
@dr-eck I upgraded the project for VS19. Since I did this before work I had not enough time to compile it (guess I am currently missing the VS Extensions package). I will do so later, but the changes are pushed. So you could compile it yourself.

Thus I also couldn't test it, so please report any issues if there are breaking changes in Visual Studio 2019.

**Comment by dr-eck** [comment]
Manuel,

            Thank you very much!  I’ve never created a VS extension package, so I’ll wait until I hear that you have compiled and checked it.

 

Steve Eckhardt

**Comment by Skyppid** [comment]
Hi @dr-eck, sorry for the long wait. I hadn't really time to work on this. Yet I currently struggle with lots of build issues. I might have to recreate the projects from scratch. So I can't really guarantee any update soon. I'm very sorry for that.

**Comment by dr-eck** [comment]
Hi Manuel,

            I understand not having time and I really appreciate your efforts.

 

Best regards,

Steve Eckhardt

**Comment by Skyppid** [comment]
Good news! It seems this was due to targeting .Net 4.6.2. I changed the target framework to 4.7.2 (shouldn't be an issue since this is well supported by VS 2019) and it compiled. I tested it quickly and it did run without any issues.

**Comment by dr-eck** [comment]
Wonderful!  Thank you very much.

 

Steve Eckhardt
